config/routes.rb
Rails.application.routes.draw do
  resources :home, :only => [:index]

  namespace :admin do
    scope :banners, :as => :banner do
      resources :homepages, :controller => :banners, :type => "Banner::Homepage" do
      end

      resources :pages, :controller => :banners, :type => "Banner::Page" do
      end
    end
    root 'banners#index', :type => "Banner::Homepage"
  end

  root 'home#index'

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  has_attached_file :attachment,
  :s3_credentials => 
    {
      :access_key_id      => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key  => ENV['AWS_SECRET_ACCESS_KEY'],
      :bucket             => ENV['S3_BUCKET_NAME']
    },
  :storage      => :s3,
  :s3_headers   => { "Cache-Control" => "max-age=31557600" },
  :s3_protocol  => "https",
  :bucket       => ENV['S3_BUCKET_NAME'],
  :url          => ":s3_domain_url",
  :styles => {},
  :default_style    => "product",
  :path             => "/banner/:id/:basename.:extension",
  :default_url      => "/banner/:id/:basename.:extension",
  :convert_options  => { all: '-strip -auto-orient -colorspace sRGB' }

  validates_attachment :attachment,
    :presence => true,
    :content_type => { :content_type => %w(image/jpeg image/jpg image/png image/gif) }

  def class_name_display
    self.class.to_s.split('::').join(' ')
  end
end

app/models/banner/homepage.rb
class Banner::Homepage < Banner
end

app/models/banner/page.rb
class Banner::Page < Banner
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < ApplicationController
  before_filter :load_banner
  helper_method :page_title

  def create
    if @banner.update_attributes(banner_params)
      flash[:notice] = "#{@banner.class_name_display} '#{@banner.name}' was successfully created."
      redirect_to [:admin, @banner.class]
    else
      flash[:alert] = "#{@banner.class_name_display} cannot create: #{@banner.errors.full_messages.join('. ')}" 
      render :edit
    end
  end

  def update
    if @banner.update_attributes(banner_params)
      flash[:notice] = "#{@banner.class_name_display} '#{@banner.name}' was successfully updated."
      redirect_to [:admin, @banner.class]
    else
      flash[:alert] = "#{@banner.class_name_display} '#{@banner.name}' cannot update: #{@banner.errors.full_messages.join('. ')}" 
      render :edit
    end
  end

  def destroy
    if @banner && @banner.destroy
      flash[:notice] = "#{@banner.class_name_display} '#{@banner.name}' was successfully destroyed."
    else
      flash[:alert] = "#{@banner.class_name_display} '#{@banner.name}' cannot destroy: #{@banner.errors.full_messages.join('. ')}" 
    end
    
    redirect_to :back
  end

  private
  def banner_params
    params_key = params.has_key?(:banner_homepage) ? :banner_homepage : :banner_page
    params.require(params_key).permit(:name, :type, :attachment, :active, :position, :data)
  end

  def load_banner
    if %w(index).include? action_name
      @banners = resource.order(:position)
    else
      @banner = params[:id].present? ? resource.find(params[:id]) : resource.new
    end
  end

  def resource
    @resource ||= params[:type].singularize.titleize.camelize.constantize
  end

  def page_title 
    params[:type].to_s.split('::').join(' ') rescue ''
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/banners/_form.html.haml
.row
  .col-sm-6
    = f.label :name, 'Name*'
    = f.text_field :name, :required => true
  .col-sm-6
    - size = params[:type] == 'Spree::Banner::Homepage' ? '960x330' : '960x95'
    = f.label :attachment, "Attachment* (#{size})"
    = f.file_field :attachment, onchange: 'Attachment.UpdatePreview(this)', required: f.object.new_record?
%br/
.row
  .col-sm-6
    %label{:for => ""} Preview
    - image_url = f.object.attachment.url rescue "http://www.parentcenterhub.org/wp-content/uploads/2014/03/No-Image-.jpg"
    = image_tag image_url, :class => 'img-responsive', id:"image-preview"
  .col-sm-6
    %label.no-padding
      = f.check_box :active
      %span.title-5.margin-left-5 Active

:javascript
  $(function(){
    Attachment = {
      UpdatePreview: function(obj){
        if(!window.FileReader){
        } else {
          var reader = new FileReader();
          var target = null;
          reader.onload = function(e) {
            target =  e.target || e.srcElement;
            $("#image-preview").prop("src", target.result);
          };
          reader.readAsDataURL(obj.files[0]);
        }
      }
    };
  });

app/views/admin/banners/edit.html.haml
= content_for :right_nav_bar do
  %li
    = link_to "Back to #{@banner.class_name_display} List", [:admin, @banner.class]

= form_for [:admin, @banner] do |f|
  = render :partial => 'form', :locals => { :f => f }
  .form-buttons.filter-actions.actions.text-right{"data-hook" => "buttons"}
    = link_to "Cancel",  [:admin, @banner.class], :class => 'btn btn-sm btn-default'
    = f.submit :update, :class => 'btn btn-sm btn-success'

app/views/admin/banners/index.html.haml
= content_for :right_nav_bar do
  %li
    = link_to "New #{page_title}", [:new, :admin, @resource.model_name.param_key]

%table.table.table-style-1
  %thead
    %tr
      %th Name
      %th File Name
      %th Thumbs
      %th{:style => 'width: 75px;'} Status
      %th Actions
  %tbody
    - @banners.each do |banner|
      %tr
        %td= banner.name
        %td= banner.attachment_file_name
        %td= image_tag banner.attachment.url, :width => '70px'
        %td.text-center.margin-0.padding-0
          = content_tag :div, :class => "state #{banner.active ? 'text-success' : 'text-danger'}" do
            = "#{banner.active ? 'Active' : 'Inactive'}"
        %td.actions.actions-2
          = link_to 'edit', [:edit, :admin, banner], :class => 'edit-button btn btn-sm btn-primary'
          = link_to 'delete', [:admin, banner], :class => 'delete-button btn btn-sm btn-danger', method: :delete, :data => { :confirm => "Are you sure?"}

app/views/admin/banners/new.html.haml
= content_for :right_nav_bar do
  %li
    = link_to "Back to #{@banner.class_name_display} List", [:admin, @banner.class]

= form_for [:admin, @banner] do |f|
  = render :partial => 'form', :locals => { :f => f }
  .form-buttons.filter-actions.actions.text-right{"data-hook" => "buttons"}
    = link_to "Cancel",  [:admin, @banner.class], :class => 'btn btn-sm btn-default'
    = f.submit :create, :class => 'btn btn-sm btn-success'

app/views/home/index.html.haml
.text-center
  = link_to "Access Admin", admin_root_path, :class => 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title STI Example
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / Latest compiled and minified CSS
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", :integrity => "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", :rel => "stylesheet"}/
    / Latest compiled and minified JavaScript
    %script{:crossorigin => "anonymous", :integrity => "sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"}
  %body
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} STI EXAMPLE
        .navbar-header.pull-right{:style => "margin-left: 15px"}
          %a.navbar-brand{:href => "https://github.com/hoanghiepitvnn/rails-sti-example"}
            %img{:alt => "Brand", :src => "https://assets-cdn.github.com/favicon.ico", :height => 20}/
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if params[:type].present?
              %li{:role => "presentation", :class => "#{params[:type] == 'Banner::Homepage' ? 'active' : '' }"}
                = link_to "BANNER HOMEPAGES", [:admin, :banner, :homepages]
              %li{:role => "presentation", :class => "#{params[:type] == 'Banner::Page' ? 'active' : '' }"}
                = link_to "BANNER PAGES", [:admin, :banner, :pages]
          %ul.nav.navbar-nav.navbar-right
            = yield :right_nav_bar
    .container
      = yield